[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-p_os_2.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
